server:
  port: 9999
  display-name: signle-sign-on
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
security:
  basic:
    enabled: false #开启认证
  user:
    name: guest
    password: guest
dcommons-token:
  cookieName: boot_jwt
  secret: xxx
  expSeconds: 86400
  refreshIntervalSeconds: 900
# 登录用户名 密码
login:
  username: admin
  password: 123